name:  Test Manual Workflow

on:
    workflow_dispatch: 
        Environment:
          description: "The environment I need to deploy on"
          required: true
          default: '/dev'

jobs: 
    manual-job:
        runs-on: ubuntu-latest

        steps:
          - name: Exemple
          run: echo "Mon exemple" 
